# Extração

In [1]:
import pandas as pd
import numpy as np

vendas = pd.read_csv('dados/Vendas.csv', sep=';')
clientes = pd.read_csv('dados/Clientes.csv', sep=';')
pedidos = pd.read_csv('dados/Pedidos.csv', sep=';')
produtos = pd.read_csv('dados/Produtos.csv', sep=';')

## Checagem e Processamento

In [2]:
vendas.info()
clientes.info()
pedidos.info()
produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Pedido              51290 non-null  object
 1   Cliente             51290 non-null  object
 2   Produto             51290 non-null  object
 3   Valor Venda         51290 non-null  object
 4   Quantidade Vendida  51290 non-null  int64
 5   Custo Envio         51290 non-null  object
dtypes: int64(1), object(5)
memory usage: 2.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1590 entries, 0 to 1589
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID Cliente    1590 non-null   object
 1   Nome Cliente  1590 non-null   object
 2   Segmento      1590 non-null   object
 3   Cidade        1590 non-null   object
 4   Estado        1590 non-null   object
 5   Pais          1590 non-null   object
 6   Mercado       1590 non-null   object
 7   Regiao        1590 non-null   object
dtypes: object(8)
memory usage: 99.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25036 entries, 0 to 25035
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Local Pedido       25036 non-null  object
 1   Ano                25036 non-null  int64
 2   ID Pedido          25036 non-null  int64
 3   Data Pedido        25036 non-null  object
 4   Data Envio         25036 non-null  object
 5   Modo Envio         25036 non-null  object
 6   Prioridade Pedido  25036 non-null  object
dtypes: int64(2), object(5)
memory usage: 1.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10293 entries, 0 to 10292
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID Produto    10293 non-null  object
 1   Categoria     10293 non-null  object
 2   SubCategoria  10293 non-null  object
 3   Nome Produto  10293 non-null  object
dtypes: object(4)
memory usage: 321.8+ KB

In [3]:
vendas.head()

,Pedido,Cliente,Produto,Valor Venda,Quantidade Vendida,Custo Envio
0,CA-2012-124891,RH-19495,TEC-AC-10003033,"2309,65",7,"933,57"
1,IN-2013-77878,JR-16210,FUR-CH-10003950,"3709,395",9,"923,63"
2,IN-2013-71249,CR-12730,TEC-PH-10004664,"5175,171",9,"915,49"
3,ES-2013-1579342,KM-16375,TEC-PH-10004583,"2892,51",5,"910,16"
4,SG-2013-4320,RH-9495,TEC-SHA-10000501,"2832,96",8,"903,04"

In [4]:
vendas.columns

Index(['Pedido', 'Cliente', 'Produto', 'Valor Venda', 'Quantidade Vendida',
       'Custo Envio'],
      dtype='object')

In [5]:
vendas.isnull().sum()

Pedido                0
Cliente               0
Produto               0
Valor Venda           0
Quantidade Vendida    0
Custo Envio           0
dtype: int64

In [6]:
vendas.duplicated().sum()

np.int64(0)

In [7]:
clientes.head()

,ID Cliente,Nome Cliente,Segmento,Cidade,Estado,Pais,Mercado,Regiao
0,RH-19495,Rick Hansen,Consumidor,New York City,New York,United States,US,East
1,JR-16210,Justin Ritter,Corporativo,Wollongong,New South Wales,Australia,APAC,Oceania
2,CR-12730,Craig Reiter,Consumidor,Brisbane,Queensland,Australia,APAC,Oceania
3,KM-16375,Katherine Murray,Outros,Berlin,Berlin,Germany,EU,Central
4,RH-9495,Rick Hansen,Consumidor,Dakar,Dakar,Senegal,Africa,Africa

In [8]:
clientes.columns

Index(['ID Cliente', 'Nome Cliente', 'Segmento', 'Cidade', 'Estado', 'Pais',
       'Mercado', 'Regiao'],
      dtype='object')

In [9]:
clientes.isnull().sum()

ID Cliente      0
Nome Cliente    0
Segmento        0
Cidade          0
Estado          0
Pais            0
Mercado         0
Regiao          0
dtype: int64

In [10]:
clientes.duplicated().sum()

np.int64(0)

In [11]:
pedidos.head()

,Local Pedido,Ano,ID Pedido,Data Pedido,Data Envio,Modo Envio,Prioridade Pedido
0,CA,2012,124891,31/07/2012,31/07/2012,Mesmo Dia,Critico
1,CA,2012,124891,31/07/2012,31/07/2012,Mesmo Dia,Critico
2,IN,2013,77878,05/02/2013,07/02/2013,Segunda Classe,Critico
3,IN,2013,71249,17/10/2013,18/10/2013,Primeira Classe,Medio
4,ES,2013,1579342,28/01/2013,30/01/2013,Primeira Classe,Medio

In [12]:
pedidos.columns

Index(['Local Pedido', 'Ano', 'ID Pedido', 'Data Pedido', 'Data Envio',
       'Modo Envio', 'Prioridade Pedido'],
      dtype='object')

In [13]:
pedidos = pedidos.drop_duplicates()

In [14]:
pedidos.isnull().sum()

Local Pedido         0
Ano                  0
ID Pedido            0
Data Pedido          0
Data Envio           0
Modo Envio           0
Prioridade Pedido    0
dtype: int64

In [15]:
pedidos.duplicated().sum()

np.int64(0)

In [16]:
produtos.head()

,ID Produto,Categoria,SubCategoria,Nome Produto
0,TEC-AC-10003033,Tecnologia,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...
1,TEC-AC-10003033,Tecnologia,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...
2,FUR-CH-10003950,Moveis,Chairs,"Novimex Executive Leather Armchair, Black"
3,TEC-PH-10004664,Tecnologia,Phones,"Nokia Smart Phone, with Caller ID"
4,TEC-PH-10004583,Tecnologia,Phones,"Motorola Smart Phone, Cordless"

In [17]:
produtos.columns

Index(['ID Produto', 'Categoria', 'SubCategoria', 'Nome Produto'], dtype='object')

In [18]:
produtos.isnull().sum()

ID Produto      0
Categoria       0
SubCategoria    0
Nome Produto    0
dtype: int64

In [19]:
produtos.duplicated().sum()

np.int64(1)

In [20]:
produtos = produtos.drop_duplicates()

# Transformação

## 1    -   Tratamentos Gerais

### Conversão de datas

In [21]:
pedidos['Data Pedido'] = pd.to_datetime(pedidos['Data Pedido'], dayfirst=True)
pedidos['Data Envio'] = pd.to_datetime(pedidos['Data Envio'], dayfirst=True)
pedidos

,Local Pedido,Ano,ID Pedido,Data Pedido,Data Envio,Modo Envio,Prioridade Pedido
0,CA,2012,124891,2012-07-31,2012-07-31,Mesmo Dia,Critico
2,IN,2013,77878,2013-02-05,2013-02-07,Segunda Classe,Critico
3,IN,2013,71249,2013-10-17,2013-10-18,Primeira Classe,Medio
4,ES,2013,1579342,2013-01-28,2013-01-30,Primeira Classe,Medio
5,SG,2013,4320,2013-11-05,2013-11-06,Mesmo Dia,Critico
...,...,...,...,...,...,...,...
25031,ZI,2011,4350,2011-03-21,2011-03-26,Classe Padrao,Medio
25032,MX,2014,169530,2014-06-09,2014-06-11,Primeira Classe,Alto
25033,IN,2014,72327,2014-05-30,2014-05-30,Mesmo Dia,Alto
25034,IN,2014,57662,2014-08-05,2014-08-10,Classe Padrao,Medio
25035,MX,2012,134460,2012-05-22,2012-05-26,Segunda Classe,Alto

### Renomear colunas

In [22]:
vendas = vendas.rename(columns={'Pedido': 'id_pedido',
                                 'Cliente': 'id_cliente',
                                 'Produto': 'id_produto',
                                 'Valor Venda': 'valor_venda',
                                 'Quantidade Vendida': 'qtd_vendida',
                                 'Custo Envio': 'custo_envio'})

pedidos = pedidos.rename(columns={'Local Pedido': 'local_pedido',
                                  'Ano': 'ano',
                                  'ID Pedido': 'pedido_num',
                                   'Data Pedido': 'data_pedido',
                                   'Data Envio': 'data_envio',
                                   'Modo Envio': 'modo_envio',
                                   'Prioridade Pedido': 'prioridade'})

clientes = clientes.rename(columns={'ID Cliente': 'id_cliente',
                                    'Nome Cliente': 'nome_cliente',
                                    'Segmento': 'segmento',
                                    'Cidade': 'cidade',
                                    'Estado': 'estado',
                                    'Pais': 'pais',
                                    'Mercado': 'mercado',
                                    'Regiao': 'regiao'})

produtos = produtos.rename(columns={'ID Produto': 'id_produto',
                                    'Categoria': 'categoria',
                                    'SubCategoria': 'subcategoria',
                                    'Nome Produto': 'nome_produto'})

### Conversão de valores

In [23]:
vendas['valor_venda'] = vendas['valor_venda'].str.replace(',', '.').astype(float)
vendas['custo_envio'] = vendas['custo_envio'].str.replace(',', '.').astype(float)

### Crianção de novas colunas preco_unitario na tabela vendas e id_pedido na tabela pedidos

In [24]:
vendas['valor_unit'] = vendas['valor_venda'] / vendas['qtd_vendida']
pedidos['id_pedido'] = pedidos['local_pedido'].astype(str) + '-' + pedidos['ano'].astype(str) + '-' + pedidos['pedido_num'].astype(str)

## 2    -   Tabela dim_produtos

### Contar quantidade de ocorrências por nome_produto > 1

In [25]:
contagem = produtos['nome_produto'].value_counts().reset_index()
contagem.columns = ['nome_produto', 'Quantidade']
num_produtos_repetidos = contagem[contagem['Quantidade'] > 1]
num_produtos_repetidos

                                 nome_produto  Quantidade
0                                     Staples          45
1       Stockwell Paper Clips, Assorted Sizes          16
2                       Acco Index Tab, Clear          12
3               Bush Stackable Bookrack, Pine          11
4                Stockwell Thumb Tacks, Metal          11
...                                       ...         ...
1933               Advantus Light Bulb, Black           2
1934                Panasonic Inkjet, Durable           2
1935  Hon Computer Table, with Bottom Storage           2
1936                 Prang Drawing Pencil Set           2
1937           Bevis Round Table, Rectangular           2

[1938 rows x 2 columns]

### Filtrando no dataframe original os produtos que estão repetidos

In [26]:
produtos_repetidos = produtos[produtos['nome_produto'].isin(num_produtos_repetidos['nome_produto'])]
produtos_repetidos

,id_produto,categoria,subcategoria,nome_produto
2,FUR-CH-10003950,Moveis,Chairs,"Novimex Executive Leather Armchair, Black"
3,TEC-PH-10004664,Tecnologia,Phones,"Nokia Smart Phone, with Caller ID"
4,TEC-PH-10004583,Tecnologia,Phones,"Motorola Smart Phone, Cordless"
5,TEC-SHA-10000501,Tecnologia,Copiers,"Sharp Wireless Fax, High-Speed"
6,TEC-PH-10000030,Tecnologia,Phones,"Samsung Smart Phone, with Caller ID"
...,...,...,...,...
10287,OFF-SME-10000950,Material de Escritorio,Labels,"Smead Color Coded Labels, 5000 Label Set"
10288,OFF-FA-10004112,Material de Escritorio,Fasteners,"Stockwell Staples, 12 Pack"
10289,OFF-BI-10003253,Material de Escritorio,Binders,"Ibico Index Tab, Economy"
10290,OFF-BI-10002510,Material de Escritorio,Binders,"Acco Index Tab, Clear"
10291,FUR-ADV-10002329,Moveis,Furnishings,"Advantus Light Bulb, Erganomic"

In [27]:
produtos[produtos['nome_produto'] == 'Novimex Executive Leather Armchair, Black']

,id_produto,categoria,subcategoria,nome_produto
2,FUR-CH-10003950,Moveis,Chairs,"Novimex Executive Leather Armchair, Black"
302,FUR-CH-10004669,Moveis,Chairs,"Novimex Executive Leather Armchair, Black"
2328,FUR-NOV-10004925,Moveis,Chairs,"Novimex Executive Leather Armchair, Black"
5633,FUR-CH-10002435,Moveis,Chairs,"Novimex Executive Leather Armchair, Black"

### Identificar o id_produto mais frequente para cada nome_produto

In [28]:
id_mais_frequente = produtos_repetidos.groupby('nome_produto')['id_produto'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()
id_mais_frequente

                                 nome_produto        id_produto
0     #10- 4 1/8" x 9 1/2" Recycled Envelopes   OFF-EN-10000461
1                    Acco 3-Hole Punch, Clear  OFF-ACC-10002849
2                  Acco 3-Hole Punch, Durable  OFF-ACC-10002343
3                  Acco 3-Hole Punch, Economy  OFF-ACC-10000808
4                 Acco 3-Hole Punch, Recycled  OFF-ACC-10004692
...                                       ...               ...
1933               Xerox Note Cards, Recycled   OFF-PA-10001448
1934          Xerox Parchment Paper, 8.5 x 11   OFF-PA-10000098
1935        Xerox Parchment Paper, Multicolor   OFF-PA-10000872
1936           Xerox Parchment Paper, Premium   OFF-PA-10000116
1937          Xerox Parchment Paper, Recycled   OFF-PA-10001495

[1938 rows x 2 columns]

### Dicionário de mapeamento nome_produto → id_produto mais frequente

In [29]:
mapa_id_padronizado = dict(zip(id_mais_frequente['nome_produto'], id_mais_frequente['id_produto']))
mapa_id_padronizado

{'#10- 4 1/8" x 9 1/2" Recycled Envelopes': 'OFF-EN-10000461',
 'Acco 3-Hole Punch, Clear': 'OFF-ACC-10002849',
 'Acco 3-Hole Punch, Durable': 'OFF-ACC-10002343',
 'Acco 3-Hole Punch, Economy': 'OFF-ACC-10000808',
 'Acco 3-Hole Punch, Recycled': 'OFF-ACC-10004692',
 'Acco Binder Covers, Clear': 'OFF-ACC-10001993',
 'Acco Binder Covers, Durable': 'OFF-ACC-10004008',
 'Acco Binder Covers, Economy': 'OFF-ACC-10004871',
 'Acco Binder Covers, Recycled': 'OFF-ACC-10004538',
 'Acco Binder, Clear': 'OFF-ACC-10004322',
 'Acco Binder, Durable': 'OFF-ACC-10003422',
 'Acco Binder, Economy': 'OFF-ACC-10000233',
 'Acco Binder, Recycled': 'OFF-ACC-10001703',
 'Acco Binding Machine, Clear': 'OFF-ACC-10000102',
 'Acco Binding Machine, Durable': 'OFF-ACC-10003636',
 'Acco Binding Machine, Economy': 'OFF-ACC-10002220',
 'Acco Binding Machine, Recycled': 'OFF-ACC-10002680',
 'Acco Hole Reinforcements, Clear': 'OFF-ACC-10003788',
 'Acco Hole Reinforcements, Durable': 'OFF-ACC-10000218',
 'Acco Hole Reinforcements, Economy': 'OFF-ACC-10000798',
 'Acco Hole Reinforcements, Recycled': 'OFF-ACC-10004281',
 'Acco Index Tab, Clear': 'OFF-ACC-10000307',
 'Acco Index Tab, Durable': 'OFF-ACC-10004182',
 'Acco Index Tab, Economy': 'OFF-ACC-10002772',
 'Accos Clamps, 12 Pack': 'OFF-ACC-10000687',
 'Accos Clamps, Assorted Sizes': 'OFF-ACC-10003713',
 'Accos Clamps, Bulk Pack': 'OFF-ACC-10001281',
 'Accos Clamps, Metal': 'OFF-ACC-10003806',
 'Accos Paper Clips, Assorted Sizes': 'OFF-ACC-10003745',
 'Accos Paper Clips, Bulk Pack': 'OFF-ACC-10004278',
 'Accos Paper Clips, Metal': 'OFF-ACC-10002167',
 'Accos Push Pins, 12 Pack': 'OFF-ACC-10004748',
 'Accos Push Pins, Assorted Sizes': 'OFF-ACC-10003909',
 'Accos Push Pins, Bulk Pack': 'OFF-ACC-10004364',
 'Accos Push Pins, Metal': 'OFF-ACC-10001028',
 'Accos Rubber Bands, 12 Pack': 'OFF-ACC-10004430',
 'Accos Rubber Bands, Assorted Sizes': 'OFF-ACC-10000497',
 'Accos Rubber Bands, Bulk Pack': 'OFF-ACC-10003265',
 'Accos Rubber Bands, Metal': 'OFF-ACC-10004910',
 'Accos Staples, 12 Pack': 'OFF-ACC-10000375',
 'Accos Staples, Assorted Sizes': 'OFF-ACC-10004713',
 'Accos Staples, Bulk Pack': 'OFF-ACC-10003925',
 'Accos Staples, Metal': 'OFF-ACC-10004782',
 'Accos Thumb Tacks, 12 Pack': 'OFF-ACC-10002834',
 'Accos Thumb Tacks, Assorted Sizes': 'OFF-ACC-10002425',
 'Accos Thumb Tacks, Bulk Pack': 'OFF-ACC-10002853',
 'Accos Thumb Tacks, Metal': 'OFF-ACC-10002327',
 'Acme Box Cutter, Easy Grip': 'OFF-ACM-10001587',
 'Acme Box Cutter, High Speed': 'OFF-SU-10001657',
 'Acme Box Cutter, Serrated': 'OFF-ACM-10001029',
 'Acme Box Cutter, Steel': 'OFF-ACM-10002713',
 'Acme Letter Opener, Easy Grip': 'OFF-ACM-10000476',
 'Acme Letter Opener, High Speed': 'OFF-ACM-10000570',
 'Acme Letter Opener, Serrated': 'OFF-ACM-10001704',
 'Acme Letter Opener, Steel': 'OFF-ACM-10002816',
 'Acme Ruler, Easy Grip': 'OFF-ACM-10002131',
 'Acme Ruler, High Speed': 'OFF-ACM-10000277',
 'Acme Ruler, Serrated': 'OFF-ACM-10004150',
 'Acme Ruler, Steel': 'OFF-ACM-10000671',
 'Acme Scissors, Easy Grip': 'OFF-ACM-10004895',
 'Acme Scissors, High Speed': 'OFF-ACM-10003510',
 'Acme Scissors, Serrated': 'OFF-ACM-10000777',
 'Acme Scissors, Steel': 'OFF-ACM-10004587',
 'Acme Shears, Easy Grip': 'OFF-ACM-10004669',
 'Acme Shears, High Speed': 'OFF-ACM-10002045',
 'Acme Shears, Serrated': 'OFF-ACM-10003715',
 'Acme Shears, Steel': 'OFF-ACM-10001112',
 'Acme Trimmer, Easy Grip': 'OFF-ACM-10003278',
 'Acme Trimmer, High Speed': 'OFF-ACM-10003978',
 'Acme Trimmer, Serrated': 'OFF-ACM-10002301',
 'Acme Trimmer, Steel': 'OFF-ACM-10003591',
 'Advantus Clamps, 12 Pack': 'OFF-ADV-10001124',
 'Advantus Clamps, Assorted Sizes': 'OFF-ADV-10001451',
 'Advantus Clamps, Bulk Pack': 'OFF-ADV-10002593',
 'Advantus Clamps, Metal': 'OFF-ADV-10000425',
 'Advantus Clock, Black': 'FUR-ADV-10004223',
 'Advantus Clock, Duo Pack': 'FUR-ADV-10000600',
 'Advantus Clock, Durable': 'FUR-ADV-10002889',
 'Advantus Clock, Erganomic': 'FUR-ADV-10000108',
 'Advantus Door Stop, Black': 'FUR-ADV-10001440',
 'Advantus Door Stop, Duo Pack': 'FUR-ADV-10002632',
 'Advantus Door Stop, Durable': 'FUR-ADV-10004395',
 'Advantus Door Stop, Erganomic': 'FUR-ADV-10004971',
 'Advantus Frame, Black': 'FUR-ADV-10001283',
 'Advantus Frame, Duo Pack': 'FUR-ADV-10000190',
 'Advantus Frame, Durable': 'FUR-ADV-10004159',
 'Advantus Frame, Erganomic': 'FUR-ADV-10000571',
 'Advantus Light Bulb, Black': 'FUR-ADV-10003326',
 'Advantus Light Bulb, Duo Pack': 'FUR-ADV-10004718',
 'Advantus Light Bulb, Durable': 'FUR-ADV-10001659',
 'Advantus Light Bulb, Erganomic': 'FUR-ADV-10002329',
 'Advantus Paper Clips, Assorted Sizes': 'OFF-ADV-10000331',
 'Advantus Paper Clips, Bulk Pack': 'OFF-ADV-10001437',
 'Advantus Paper Clips, Metal': 'OFF-ADV-10004598',
 'Advantus Photo Frame, Black': 'FUR-ADV-10000183',
 'Advantus Photo Frame, Duo Pack': 'FUR-ADV-10000002',
 'Advantus Photo Frame, Durable': 'FUR-ADV-10004499',
 'Advantus Photo Frame, Erganomic': 'FUR-ADV-10002601',
 'Advantus Push Pins, 12 Pack': 'OFF-ADV-10000308',
 'Advantus Push Pins, Assorted Sizes': 'OFF-ADV-10004228',
 'Advantus Push Pins, Bulk Pack': 'OFF-FA-10001815',
 'Advantus Push Pins, Metal': 'OFF-ADV-10004030',
 'Advantus Rubber Bands, 12 Pack': 'OFF-ADV-10002299',
 'Advantus Rubber Bands, Assorted Sizes': 'OFF-ADV-10002549',
 'Advantus Rubber Bands, Bulk Pack': 'OFF-ADV-10003050',
 'Advantus Rubber Bands, Metal': 'OFF-ADV-10000213',
 'Advantus Stacking Tray, Black': 'FUR-ADV-10000847',
 'Advantus Stacking Tray, Durable': 'FUR-ADV-10001855',
 'Advantus Stacking Tray, Erganomic': 'FUR-ADV-10000188',
 'Advantus Staples, 12 Pack': 'OFF-ADV-10003030',
 'Advantus Staples, Assorted Sizes': 'OFF-ADV-10003196',
 'Advantus Staples, Bulk Pack': 'OFF-ADV-10004875',
 'Advantus Staples, Metal': 'OFF-ADV-10000177',
 'Advantus Thumb Tacks, 12 Pack': 'OFF-ADV-10004241',
 'Advantus Thumb Tacks, Assorted Sizes': 'OFF-ADV-10003369',
 'Advantus Thumb Tacks, Bulk Pack': 'OFF-ADV-10000551',
 'Advantus Thumb Tacks, Metal': 'OFF-ADV-10004274',
 'Ames Business Envelopes, Recycled': 'OFF-AME-10002557',
 'Ames Business Envelopes, Security-Tint': 'OFF-AME-10002956',
 'Ames Business Envelopes, Set of 50': 'OFF-AME-10003180',
 'Ames Clasp Envelope, Recycled': 'OFF-AME-10003167',
 'Ames Clasp Envelope, Security-Tint': 'OFF-AME-10003089',
 'Ames Clasp Envelope, Set of 50': 'OFF-AME-10002923',
 'Ames Clasp Envelope, with clear poly window': 'OFF-AME-10002949',
 'Ames Interoffice Envelope, Recycled': 'OFF-AME-10001641',
 'Ames Interoffice Envelope, Security-Tint': 'OFF-AME-10000360',
 'Ames Interoffice Envelope, Set of 50': 'OFF-AME-10001009',
 'Ames Interoffice Envelope, with clear poly window': 'OFF-AME-10000440',
 'Ames Mailers, Recycled': 'OFF-AME-10004651',
 'Ames Mailers, Security-Tint': 'OFF-EN-10000069',
 'Ames Mailers, Set of 50': 'OFF-AME-10001179',
 'Ames Mailers, with clear poly window': 'OFF-AME-10000851',
 'Ames Manila Envelope, Recycled': 'OFF-AME-10002376',
 'Ames Manila Envelope, Security-Tint': 'OFF-AME-10000244',
 'Ames Manila Envelope, Set of 50': 'OFF-AME-10001489',
 'Ames Manila Envelope, with clear poly window': 'OFF-AME-10004759',
 'Ames Peel and Seal, Recycled': 'OFF-AME-10000870',
 'Ames Peel and Seal, Security-Tint': 'OFF-AME-10002081',
 'Ames Peel and Seal, Set of 50': 'OFF-AME-10002652',
 'Ames Peel and Seal, with clear poly window': 'OFF-AME-10001587',
 'Apple Audio Dock, Cordless': 'TEC-APP-10003032',
 'Apple Audio Dock, Full Size': 'TEC-APP-10002829',
 'Apple Audio Dock, VoIP': 'TEC-APP-10000530',
 'Apple Audio Dock, with Caller ID': 'TEC-APP-10001389',
 'Apple Headset, Cordless': 'TEC-APP-10001732',
 'Apple Headset, Full Size': 'TEC-APP-10001851',
 'Apple Headset, VoIP': 'TEC-APP-10001340',
 'Apple Headset, with Caller ID': 'TEC-APP-10001108',
 'Apple Office Telephone, Cordless': 'TEC-APP-10002310',
 'Apple Office Telephone, Full Size': 'TEC-APP-10001965',
 'Apple Office Telephone, VoIP': 'TEC-APP-10004584',
 'Apple Office Telephone, with Caller ID': 'TEC-APP-10000135',
 'Apple Signal Booster, Cordless': 'TEC-APP-10004469',
 'Apple Signal Booster, Full Size': 'TEC-APP-10002321',
 'Apple Signal Booster, VoIP': 'TEC-APP-10004464',
 'Apple Signal Booster, with Caller ID': 'TEC-APP-10003588',
 'Apple Smart Phone, Cordless': 'TEC-APP-10004657',
 'Apple Smart Phone, Full Size': 'TEC-APP-10000308',
 'Apple Smart Phone, with Caller ID': 'TEC-PH-10000169',
 'Apple Speaker Phone, Cordless': 'TEC-APP-10004049',
 'Apple Speaker Phone, Full Size': 'TEC-APP-10004296',
 'Apple Speaker Phone, VoIP': 'TEC-APP-10001586',
 'Apple Speaker Phone, with Caller ID': 'TEC-APP-10004912',
 'Avery 3-Hole Punch, Clear': 'OFF-AVE-10001750',
 'Avery 3-Hole Punch, Durable': 'OFF-AVE-10004909',
 'Avery 3-Hole Punch, Economy': 'OFF-AVE-10002102',
 'Avery 3-Hole Punch, Recycled': 'OFF-AVE-10002892',
 'Avery Binder Covers, Clear': 'OFF-AVE-10000357',
 'Avery Binder Covers, Durable': 'OFF-AVE-10002311',
 'Avery Binder Covers, Economy': 'OFF-AVE-10004570',
 'Avery Binder Covers, Recycled': 'OFF-AVE-10004827',
 'Avery Binder, Clear': 'OFF-AVE-10001847',
 'Avery Binder, Durable': 'OFF-AVE-10004308',
 'Avery Binder, Economy': 'OFF-AVE-10003465',
 'Avery Binder, Recycled': 'OFF-AVE-10004708',
 'Avery Binding Machine, Clear': 'OFF-AVE-10003740',
 'Avery Binding Machine, Durable': 'OFF-AVE-10002079',
 'Avery Binding Machine, Economy': 'OFF-AVE-10004251',
 'Avery Binding Machine, Recycled': 'OFF-AVE-10003549',
 'Avery Color Coded Labels, 5000 Label Set': 'OFF-AVE-10000418',
 'Avery Color Coded Labels, Adjustable': 'OFF-AVE-10000894',
 'Avery Color Coded Labels, Alphabetical': 'OFF-AVE-10004412',
 'Avery Color Coded Labels, Laser Printer Compatible': 'OFF-AVE-10004148',
 'Avery File Folder Labels, 5000 Label Set': 'OFF-AVE-10004159',
 'Avery File Folder Labels, Adjustable': 'OFF-LA-10000738',
 'Avery File Folder Labels, Alphabetical': 'OFF-AVE-10004310',
 'Avery File Folder Labels, Laser Printer Compatible': 'OFF-AVE-10001079',
 'Avery Hole Reinforcements, Clear': 'OFF-AVE-10000543',
 'Avery Hole Reinforcements, Durable': 'OFF-AVE-10003279',
 'Avery Hole Reinforcements, Economy': 'OFF-AVE-10004512',
 'Avery Hole Reinforcements, Recycled': 'OFF-AVE-10004556',
 'Avery Index Tab, Clear': 'OFF-AVE-10000432',
 'Avery Index Tab, Durable': 'OFF-AVE-10002024',
 'Avery Index Tab, Economy': 'OFF-AVE-10000608',
 'Avery Legal Exhibit Labels, 5000 Label Set': 'OFF-AVE-10003504',
 'Avery Legal Exhibit Labels, Adjustable': 'OFF-AVE-10000585',
 'Avery Legal Exhibit Labels, Alphabetical': 'OFF-AVE-10001367',
 'Avery Legal Exhibit Labels, Laser Printer Compatible': 'OFF-AVE-10001473',
 'Avery Removable Labels, 5000 Label Set': 'OFF-LA-10001541',
 'Avery Removable Labels, Adjustable': 'OFF-AVE-10000802',
 'Avery Removable Labels, Alphabetical': 'OFF-AVE-10000065',
 'Avery Removable Labels, Laser Printer Compatible': 'OFF-AVE-10004828',
 'Avery Round Labels, 5000 Label Set': 'OFF-AVE-10004732',
 'Avery Round Labels, Adjustable': 'OFF-AVE-10004508',
 'Avery Round Labels, Alphabetical': 'OFF-AVE-10003558',
 'Avery Round Labels, Laser Printer Compatible': 'OFF-AVE-10000110',
 'Avery Shipping Labels, 5000 Label Set': 'OFF-AVE-10004536',
 'Avery Shipping Labels, Adjustable': 'OFF-AVE-10002014',
 'Avery Shipping Labels, Alphabetical': 'OFF-AVE-10004404',
 'Avery Shipping Labels, Laser Printer Compatible': 'OFF-AVE-10000909',
 'BIC Canvas, Blue': 'OFF-AR-10002745',
 'BIC Canvas, Easy-Erase': 'OFF-AR-10000205',
 'BIC Canvas, Fluorescent': 'OFF-AR-10000120',
 'BIC Canvas, Water Color': 'OFF-AR-10001423',
 'BIC Highlighters, Blue': 'OFF-AR-10000019',
 'BIC Highlighters, Easy-Erase': 'OFF-AR-10000502',
 'BIC Highlighters, Fluorescent': 'OFF-AR-10000314',
 'BIC Highlighters, Water Color': 'OFF-AR-10000091',
 'BIC Markers, Blue': 'OFF-AR-10000481',
 'BIC Markers, Easy-Erase': 'OFF-AR-10001418',
 'BIC Markers, Fluorescent': 'OFF-AR-10000266',
 'BIC Markers, Water Color': 'OFF-AR-10001269',
 'BIC Pencil Sharpener, Blue': 'OFF-AR-10000242',
 'BIC Pencil Sharpener, Easy-Erase': 'OFF-AR-10000513',
 'BIC Pencil Sharpener, Fluorescent': 'OFF-AR-10000543',
 'BIC Pencil Sharpener, Water Color': 'OFF-AR-10001110',
 'BIC Pens, Blue': 'OFF-AR-10000468',
 'BIC Pens, Easy-Erase': 'OFF-AR-10000711',
 'BIC Pens, Fluorescent': 'OFF-AR-10001329',
 'BIC Pens, Water Color': 'OFF-AR-10000703',
 'BIC Sketch Pad, Blue': 'OFF-AR-10000097',
 'BIC Sketch Pad, Easy-Erase': 'OFF-AR-10001068',
 'BIC Sketch Pad, Fluorescent': 'OFF-AR-10000227',
 'BIC Sketch Pad, Water Color': 'OFF-AR-10000293',
 'Barricks Coffee Table, Adjustable Height': 'FUR-BAR-10002710',
 'Barricks Coffee Table, Fully Assembled': 'FUR-BAR-10001039',
 'Barricks Coffee Table, Rectangular': 'FUR-TA-10001549',
 'Barricks Computer Table, Adjustable Height': 'FUR-BAR-10003465',
 'Barricks Computer Table, Fully Assembled': 'FUR-TA-10000317',
 'Barricks Computer Table, with Bottom Storage': 'FUR-BAR-10000946',
 'Barricks Conference Table, Adjustable Height': 'FUR-TA-10001056',
 'Barricks Conference Table, Fully Assembled': 'FUR-TA-10000184',
 'Barricks Conference Table, Rectangular': 'FUR-BAR-10003532',
 'Barricks Conference Table, with Bottom Storage': 'FUR-TA-10000671',
 'Barricks Round Table, Adjustable Height': 'FUR-TA-10001602',
 'Barricks Round Table, Fully Assembled': 'FUR-BAR-10004682',
 'Barricks Round Table, with Bottom Storage': 'FUR-BAR-10000560',
 'Barricks Training Table, Adjustable Height': 'FUR-BAR-10002449',
 'Barricks Training Table, Fully Assembled': 'FUR-BAR-10000831',
 'Barricks Training Table, Rectangular': 'FUR-BAR-10004553',
 'Barricks Training Table, with Bottom Storage': 'FUR-BAR-10003576',
 'Barricks Wood Table, Adjustable Height': 'FUR-TA-10000486',
 'Barricks Wood Table, Fully Assembled': 'FUR-BAR-10004561',
 'Barricks Wood Table, Rectangular': 'FUR-BAR-10004434',
 'Barricks Wood Table, with Bottom Storage': 'FUR-TA-10003222',
 'Belkin Flash Drive, Bluetooth': 'TEC-AC-10000284',
 'Belkin Flash Drive, Erganomic': 'TEC-AC-10001639',
 'Belkin Flash Drive, Programmable': 'TEC-AC-10001486',
 'Belkin Flash Drive, USB': 'TEC-AC-10000598',
 'Belkin Keyboard, Bluetooth': 'TEC-AC-10003556',
 'Belkin Keyboard, Erganomic': 'TEC-AC-10001311',
 'Belkin Keyboard, Programmable': 'TEC-AC-10000254',
 'Belkin Keyboard, USB': 'TEC-AC-10001075',
 'Belkin Memory Card, Bluetooth': 'TEC-AC-10001274',
 'Belkin Memory Card, Erganomic': 'TEC-AC-10002017',
 'Belkin Memory Card, Programmable': 'TEC-AC-10000221',
 'Belkin Memory Card, USB': 'TEC-AC-10002335',
 'Belkin Mouse, Bluetooth': 'TEC-AC-10000883',
 'Belkin Mouse, Erganomic': 'TEC-AC-10001407',
 'Belkin Mouse, Programmable': 'TEC-AC-10001835',
 'Belkin Mouse, USB': 'TEC-AC-10000263',
 'Belkin Numeric Keypad, Bluetooth': 'TEC-AC-10000110',
 'Belkin Numeric Keypad, Erganomic': 'TEC-AC-10000896',
 'Belkin Numeric Keypad, USB': 'TEC-AC-10000354',
 'Belkin Router, Bluetooth': 'TEC-AC-10000639',
 'Belkin Router, Erganomic': 'TEC-AC-10000866',
 'Belkin Router, Programmable': 'TEC-AC-10000335',
 'Belkin Router, USB': 'TEC-AC-10000420',
 'Bevis Coffee Table, Adjustable Height': 'FUR-TA-10000945',
 'Bevis Coffee Table, Fully Assembled': 'FUR-TA-10000075',
 'Bevis Coffee Table, Rectangular': 'FUR-BEV-10000388',
 'Bevis Computer Table, Adjustable Height': 'FUR-BEV-10001853',
 'Bevis Computer Table, Fully Assembled': 'FUR-BEV-10003414',
 'Bevis Computer Table, with Bottom Storage': 'FUR-TA-10001930',
 'Bevis Conference Table, Fully Assembled': 'FUR-BEV-10002803',
 'Bevis Conference Table, Rectangular': 'FUR-BEV-10004805',
 'Bevis Conference Table, with Bottom Storage': 'FUR-BEV-10001048',
 'Bevis Round Table, Adjustable Height': 'FUR-BEV-10002193',
 'Bevis Round Table, Fully Assembled': 'FUR-TA-10000478',
 'Bevis Round Table, Rectangular': 'FUR-TA-10001360',
 'Bevis Training Table, Adjustable Height': 'FUR-TA-10000222',
 'Bevis Training Table, Fully Assembled': 'FUR-BEV-10002369',
 'Bevis Training Table, Rectangular': 'FUR-TA-10000971',
 'Bevis Training Table, with Bottom Storage': 'FUR-TA-10001693',
 'Bevis Wood Table, Adjustable Height': 'FUR-TA-10000805',
 'Bevis Wood Table, Fully Assembled': 'FUR-BEV-10001217',
 'Bevis Wood Table, Rectangular': 'FUR-BEV-10000326',
 'Bevis Wood Table, with Bottom Storage': 'FUR-BEV-10004919',
 'Binney & Smith Canvas, Blue': 'OFF-AR-10000989',
 'Binney & Smith Canvas, Easy-Erase': 'OFF-AR-10000179',
 'Binney & Smith Canvas, Fluorescent': 'OFF-AR-10000319',
 'Binney & Smith Canvas, Water Color': 'OFF-AR-10001208',
 'Binney & Smith Highlighters, Blue': 'OFF-AR-10000751',
 'Binney & Smith Highlighters, Easy-Erase': 'OFF-AR-10003466',
 'Binney & Smith Highlighters, Fluorescent': 'OFF-AR-10000124',
 'Binney & Smith Highlighters, Water Color': 'OFF-AR-10000401',
 'Binney & Smith Markers, Blue': 'OFF-AR-10000156',
 'Binney & Smith Markers, Easy-Erase': 'OFF-AR-10000307',
 'Binney & Smith Markers, Fluorescent': 'OFF-AR-10000720',
 'Binney & Smith Markers, Water Color': 'OFF-AR-10000540',
 'Binney & Smith Pencil Sharpener, Easy-Erase': 'OFF-AR-10000027',
 'Binney & Smith Pencil Sharpener, Fluorescent': 'OFF-AR-10001898',
 'Binney & Smith Pencil Sharpener, Water Color': 'OFF-AR-10000082',
 'Binney & Smith Pens, Blue': 'OFF-AR-10001336',
 'Binney & Smith Pens, Easy-Erase': 'OFF-AR-10000505',
 'Binney & Smith Pens, Fluorescent': 'OFF-AR-10000812',
 'Binney & Smith Pens, Water Color': 'OFF-AR-10000491',
 'Binney & Smith Sketch Pad, Blue': 'OFF-AR-10000110',
 'Binney & Smith Sketch Pad, Easy-Erase': 'OFF-AR-10001546',
 'Binney & Smith Sketch Pad, Fluorescent': 'OFF-AR-10002109',
 'Binney & Smith Sketch Pad, Water Color': 'OFF-AR-10000681',
 'Boston Canvas, Blue': 'OFF-AR-10001266',
 'Boston Canvas, Easy-Erase': 'OFF-AR-10001190',
 'Boston Canvas, Fluorescent': 'OFF-AR-10002115',
 'Boston Canvas, Water Color': 'OFF-AR-10000660',
 'Boston Highlighters, Blue': 'OFF-AR-10002380',
 'Boston Highlighters, Easy-Erase': 'OFF-AR-10001833',
 'Boston Highlighters, Fluorescent': 'OFF-AR-10000356',
 'Boston Highlighters, Water Color': 'OFF-AR-10000603',
 'Boston Markers, Blue': 'OFF-AR-10000715',
 'Boston Markers, Easy-Erase': 'OFF-AR-10000539',
 'Boston Markers, Fluorescent': 'OFF-AR-10003005',
 'Boston Markers, Water Color': 'OFF-AR-10003448',
 'Boston Pencil Sharpener, Easy-Erase': 'OFF-AR-10001053',
 'Boston Pencil Sharpener, Fluorescent': 'OFF-AR-10000452',
 'Boston Pencil Sharpener, Water Color': 'OFF-AR-10000067',
 'Boston Pens, Blue': 'OFF-AR-10001645',
 'Boston Pens, Easy-Erase': 'OFF-AR-10001134',
 'Boston Pens, Fluorescent': 'OFF-AR-10000125',
 'Boston Pens, Water Color': 'OFF-AR-10000150',
 'Boston Sketch Pad, Blue': 'OFF-AR-10001708',
 'Boston Sketch Pad, Easy-Erase': 'OFF-AR-10001672',
 'Boston Sketch Pad, Fluorescent': 'OFF-AR-10002165',
 'Boston Sketch Pad, Water Color': 'OFF-AR-10001850',
 'Breville Blender, Black': 'OFF-AP-10000528',
 'Breville Blender, Silver': 'OFF-AP-10000775',
 'Breville Blender, White': 'OFF-AP-10000977',
 'Breville Coffee Grinder, Black': 'OFF-AP-10002057',
 'Breville Coffee Grinder, Red': 'OFF-AP-10002697',
 'Breville Coffee Grinder, Silver': 'OFF-AP-10000039',
 'Breville Coffee Grinder, White': 'OFF-AP-10000382',
 'Breville Microwave, Black': 'OFF-AP-10000162',
 'Breville Microwave, Red': 'OFF-AP-10000639',
 'Breville Microwave, Silver': 'OFF-AP-10000285',
 'Breville Microwave, White': 'OFF-AP-10000119',
 'Breville Refrigerator, Black': 'OFF-AP-10000108',
 'Breville Refrigerator, Red': 'OFF-AP-10000179',
 'Breville Refrigerator, Silver': 'OFF-AP-10000584',
 'Breville Refrigerator, White': 'OFF-AP-10002244',
 'Breville Stove, Black': 'OFF-AP-10001298',
 'Breville Stove, Red': 'OFF-AP-10000800',
 'Breville Stove, Silver': 'OFF-AP-10001824',
 'Breville Stove, White': 'OFF-AP-10000667',
 'Breville Toaster, Black': 'OFF-AP-10000023',
 'Breville Toaster, Red': 'OFF-AP-10001847',
 'Breville Toaster, Silver': 'OFF-AP-10000078',
 'Brother Copy Machine, Color': 'TEC-BRO-10000463',
 'Brother Copy Machine, High-Speed': 'TEC-BRO-10000348',
 'Brother Copy Machine, Laser': 'TEC-BRO-10002579',

### Criar nova coluna com id_produto padronizado

In [30]:
produtos['id_produto_padronizado'] = produtos.apply(
    lambda row: mapa_id_padronizado.get(row['nome_produto'], row['id_produto']), axis=1
)
produtos

,id_produto,categoria,subcategoria,nome_produto,id_produto_padronizado
0,TEC-AC-10003033,Tecnologia,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,TEC-AC-10003033
2,FUR-CH-10003950,Moveis,Chairs,"Novimex Executive Leather Armchair, Black",FUR-CH-10002435
3,TEC-PH-10004664,Tecnologia,Phones,"Nokia Smart Phone, with Caller ID",TEC-NOK-10000534
4,TEC-PH-10004583,Tecnologia,Phones,"Motorola Smart Phone, Cordless",TEC-MOT-10003050
5,TEC-SHA-10000501,Tecnologia,Copiers,"Sharp Wireless Fax, High-Speed",TEC-CO-10001191
...,...,...,...,...,...
10288,OFF-FA-10004112,Material de Escritorio,Fasteners,"Stockwell Staples, 12 Pack",OFF-FA-10000067
10289,OFF-BI-10003253,Material de Escritorio,Binders,"Ibico Index Tab, Economy",OFF-BI-10002414
10290,OFF-BI-10002510,Material de Escritorio,Binders,"Acco Index Tab, Clear",OFF-ACC-10000307
10291,FUR-ADV-10002329,Moveis,Furnishings,"Advantus Light Bulb, Erganomic",FUR-ADV-10002329
10292,OFF-AP-10002203,Material de Escritorio,Appliances,Eureka Disposable Bags for Sanitaire Vibra Gro...,OFF-AP-10002203

### Merge com a tabela vendas para associar os id's padronizados

In [31]:
vendas_com_id = vendas.merge(
    produtos[['id_produto', 'id_produto_padronizado']],
    on='id_produto',
    how='left'
)
vendas_com_id.head(5)

,id_pedido,id_cliente,id_produto,valor_venda,qtd_vendida,custo_envio,valor_unit,id_produto_padronizado
0,CA-2012-124891,RH-19495,TEC-AC-10003033,2309.650,7,933.57,329.950,TEC-AC-10003033
1,IN-2013-77878,JR-16210,FUR-CH-10003950,3709.395,9,923.63,412.155,FUR-CH-10002435
2,IN-2013-71249,CR-12730,TEC-PH-10004664,5175.171,9,915.49,575.019,TEC-NOK-10000534
3,ES-2013-1579342,KM-16375,TEC-PH-10004583,2892.510,5,910.16,578.502,TEC-MOT-10003050
4,SG-2013-4320,RH-9495,TEC-SHA-10000501,2832.960,8,903.04,354.120,TEC-CO-10001191

### Checagem comparativa

In [32]:
vendas_com_id[vendas_com_id['id_produto'] != vendas_com_id['id_produto_padronizado']]

,id_pedido,id_cliente,id_produto,valor_venda,qtd_vendida,custo_envio,valor_unit,id_produto_padronizado
1,IN-2013-77878,JR-16210,FUR-CH-10003950,3709.395,9,923.63,412.155,FUR-CH-10002435
2,IN-2013-71249,CR-12730,TEC-PH-10004664,5175.171,9,915.49,575.019,TEC-NOK-10000534
3,ES-2013-1579342,KM-16375,TEC-PH-10004583,2892.510,5,910.16,578.502,TEC-MOT-10003050
4,SG-2013-4320,RH-9495,TEC-SHA-10000501,2832.960,8,903.04,354.120,TEC-CO-10001191
6,IN-2011-81826,TS-21340,FUR-CH-10004050,1822.080,4,894.77,455.520,FUR-CH-10000660
...,...,...,...,...,...,...,...,...
51283,IN-2014-72327,KH-16330,OFF-PA-10000215,26.940,2,0.01,13.470,OFF-EAT-10004036
51284,IN-2014-57662,DB-13270,OFF-BI-10002424,58.050,5,0.01,11.610,OFF-AVE-10003465
51285,IN-2014-62366,KE-16420,OFF-FA-10000746,65.100,5,0.01,13.020,OFF-ADV-10004241
51288,MX-2012-140767,RB-19795,OFF-BI-10000806,13.440,2,0.00,6.720,OFF-ACC-10002772
51289,MX-2012-134460,MC-18100,OFF-PA-10004155,61.380,3,0.00,20.460,OFF-EAT-10000652

In [33]:
produtos.shape

(10292, 5)

In [34]:
dim_produtos = produtos[produtos['id_produto'] == produtos['id_produto_padronizado']].copy()
dim_produtos.shape

(3660, 5)

### Criação de Surrogate Key para a tabela produtos

In [35]:
sk_produto = {nome: idx for idx, nome in enumerate(dim_produtos['nome_produto'].unique(), 1)}
dim_produtos['sk_produto'] = dim_produtos['nome_produto'].map(sk_produto)
dim_produtos

,id_produto,categoria,subcategoria,nome_produto,id_produto_padronizado,sk_produto
0,TEC-AC-10003033,Tecnologia,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,TEC-AC-10003033,1
6,TEC-PH-10000030,Tecnologia,Phones,"Samsung Smart Phone, with Caller ID",TEC-PH-10000030,2
9,OFF-BI-10003527,Material de Escritorio,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,OFF-BI-10003527,3
10,FUR-TA-10000198,Moveis,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,FUR-TA-10000198,4
11,OFF-SU-10002881,Material de Escritorio,Supplies,Martin Yale Chadless Opener Electric Letter Op...,OFF-SU-10002881,5
...,...,...,...,...,...,...
10283,OFF-SU-10001212,Material de Escritorio,Supplies,Kleencut Forged Office Shears by Acme United C...,OFF-SU-10001212,3656
10284,OFF-AP-10004655,Material de Escritorio,Appliances,Holmes Visible Mist Ultrasonic Humidifier with...,OFF-AP-10004655,3657
10285,OFF-ENE-10004866,Material de Escritorio,Paper,"Enermax Parchment Paper, 8.5 x 11",OFF-ENE-10004866,3658
10291,FUR-ADV-10002329,Moveis,Furnishings,"Advantus Light Bulb, Erganomic",FUR-ADV-10002329,3659
10292,OFF-AP-10002203,Material de Escritorio,Appliances,Eureka Disposable Bags for Sanitaire Vibra Gro...,OFF-AP-10002203,3660

### Merge tabela produtos x vendas para inserir sk_produto

In [36]:
vendas_sk_produto = vendas_com_id.merge(
    dim_produtos[['id_produto_padronizado', 'sk_produto']],
    on='id_produto_padronizado',
    how='left'
)
vendas_sk_produto.head(10)

,id_pedido,id_cliente,id_produto,valor_venda,qtd_vendida,custo_envio,valor_unit,id_produto_padronizado,sk_produto
0,CA-2012-124891,RH-19495,TEC-AC-10003033,2309.650,7,933.57,329.950,TEC-AC-10003033,1
1,IN-2013-77878,JR-16210,FUR-CH-10003950,3709.395,9,923.63,412.155,FUR-CH-10002435,1923
2,IN-2013-71249,CR-12730,TEC-PH-10004664,5175.171,9,915.49,575.019,TEC-NOK-10000534,306
3,ES-2013-1579342,KM-16375,TEC-PH-10004583,2892.510,5,910.16,578.502,TEC-MOT-10003050,391
4,SG-2013-4320,RH-9495,TEC-SHA-10000501,2832.960,8,903.04,354.120,TEC-CO-10001191,188
5,IN-2013-42360,JM-15655,TEC-PH-10000030,2862.675,5,897.35,572.535,TEC-PH-10000030,2
6,IN-2011-81826,TS-21340,FUR-CH-10004050,1822.080,4,894.77,455.520,FUR-CH-10000660,135
7,IN-2012-86369,MB-18085,FUR-TA-10002958,5244.840,6,878.38,874.140,FUR-TA-10001285,136
8,CA-2014-135909,JW-15220,OFF-BI-10003527,5083.960,5,867.69,1016.792,OFF-BI-10003527,3
9,CA-2012-116638,JH-15985,FUR-TA-10000198,4297.644,13,865.74,330.588,FUR-TA-10000198,4

## 3    -   Tabela dim_clientes

### Verificação de clientes duplicados a partir do nome

In [37]:
contagem = clientes['nome_cliente'].value_counts().reset_index()
contagem.columns = ['nome_cliente', 'Quantidade']
num_clientes_repetidos = contagem[contagem['Quantidade'] > 1]
num_clientes_repetidos

         nome_cliente  Quantidade
0         Rick Hansen           2
1       Justin Ritter           2
2        Craig Reiter           2
3    Katherine Murray           2
4         Jim Mitchum           2
..                ...         ...
790      Tony Chapman           2
791      Dan Campbell           2
792    Nicole Brennan           2
793     Vivian Mathis           2
794     Thais Sissman           2

[795 rows x 2 columns]

### Verificação a partir dos outros atributos

In [38]:
cidades_por_nome = clientes.groupby('nome_cliente')['cidade'].nunique().reset_index()
cidades_por_nome = cidades_por_nome[cidades_por_nome['cidade'] > 1]

estados_por_nome = clientes.groupby('nome_cliente')['estado'].nunique().reset_index()
estados_por_nome = estados_por_nome[estados_por_nome['estado'] > 1]

regioes_por_nome = clientes.groupby('nome_cliente')['regiao'].nunique().reset_index()
regioes_por_nome = regioes_por_nome[regioes_por_nome['regiao'] > 1]

# Descobrir todos nomes com duplicidade em cidade
duplicidades_nome_cidade = clientes.duplicated(subset=['nome_cliente', 'cidade'], keep=False)
# Mas o que você quer é: mesmo nome, cidades diferentes
nomes_varias_cidades = clientes.groupby('nome_cliente')['cidade'].nunique().reset_index()
nomes_varias_cidades = nomes_varias_cidades[nomes_varias_cidades['cidade'] > 1]

# Filtrar todos os registros de nomes com cidades diferentes
clientes_nomes_varias_cidades = clientes[clientes['nome_cliente'].isin(nomes_varias_cidades['nome_cliente'])].sort_values('nome_cliente')
clientes_nomes_varias_cidades

,id_cliente,nome_cliente,segmento,cidade,estado,pais,mercado,regiao
123,AB-10015,Aaron Bergman,Consumidor,Wuhan,Hubei,China,APAC,North Asia
1127,AB-15,Aaron Bergman,Consumidor,Mufulira,Copperbelt,Zambia,Africa,Africa
413,AH-10030,Aaron Hawkins,Corporativo,Vienna,Vienna,Austria,EU,Central
35,AH-30,Aaron Hawkins,Corporativo,Kamina,Katanga,Democratic Republic of the Congo,Africa,Africa
1401,AS-45,Aaron Smayling,Corporativo,Cape Town,Western Cape,South Africa,Africa,Africa
...,...,...,...,...,...,...,...,...
1529,YC-11895,Yoseph Carroll,Corporativo,Edmonton,Alberta,Canada,Canada,Canada
44,ZC-21910,Zuschuss Carroll,Consumidor,Berlin,Berlin,Germany,EU,Central
1589,ZC-11910,Zuschuss Carroll,Consumidor,Maiduguri,Borno,Nigeria,Africa,Africa
1103,ZD-11925,Zuschuss Donatelli,Consumidor,Arbil,Arbil,Iraq,EMEA,EMEA
1005,ZD-21925,Zuschuss Donatelli,Consumidor,Madero,Tamaulipas,Mexico,LATAM,North

### Criação da Surrogate key para tabela clientes

In [39]:
dim_clientes = clientes.copy()
sk_cliente = {cliente: idx for idx, cliente in enumerate(clientes['id_cliente'].unique(), 1)}
dim_clientes['sk_cliente'] = clientes['id_cliente'].map(sk_cliente)
dim_clientes

,id_cliente,nome_cliente,segmento,cidade,estado,pais,mercado,regiao,sk_cliente
0,RH-19495,Rick Hansen,Consumidor,New York City,New York,United States,US,East,1
1,JR-16210,Justin Ritter,Corporativo,Wollongong,New South Wales,Australia,APAC,Oceania,2
2,CR-12730,Craig Reiter,Consumidor,Brisbane,Queensland,Australia,APAC,Oceania,3
3,KM-16375,Katherine Murray,Outros,Berlin,Berlin,Germany,EU,Central,4
4,RH-9495,Rick Hansen,Consumidor,Dakar,Dakar,Senegal,Africa,Africa,5
...,...,...,...,...,...,...,...,...,...
1585,SC-10800,Stuart Calhoun,Consumidor,Benin City,Edo,Nigeria,Africa,Africa,1586
1586,BD-1500,Bradley Drucker,Consumidor,Lagos,Lagos,Nigeria,Africa,Africa,1587
1587,RC-9825,Roy Collins,Consumidor,Budapest,Budapest,Hungary,EMEA,EMEA,1588
1588,MG-7890,Michael Granlund,Outros,Istanbul,Istanbul,Turkey,EMEA,EMEA,1589
1589,ZC-11910,Zuschuss Carroll,Consumidor,Maiduguri,Borno,Nigeria,Africa,Africa,1590

### Merge tabela clientes x vendas_sk_produto para inserir sk_clientes

In [40]:
vendas_sk_clientes = vendas_sk_produto.merge(
    dim_clientes[['id_cliente', 'sk_cliente']],
    on='id_cliente',
    how='left'
)
vendas_sk_clientes.head(10)

,id_pedido,id_cliente,id_produto,valor_venda,qtd_vendida,custo_envio,valor_unit,id_produto_padronizado,sk_produto,sk_cliente
0,CA-2012-124891,RH-19495,TEC-AC-10003033,2309.650,7,933.57,329.950,TEC-AC-10003033,1,1
1,IN-2013-77878,JR-16210,FUR-CH-10003950,3709.395,9,923.63,412.155,FUR-CH-10002435,1923,2
2,IN-2013-71249,CR-12730,TEC-PH-10004664,5175.171,9,915.49,575.019,TEC-NOK-10000534,306,3
3,ES-2013-1579342,KM-16375,TEC-PH-10004583,2892.510,5,910.16,578.502,TEC-MOT-10003050,391,4
4,SG-2013-4320,RH-9495,TEC-SHA-10000501,2832.960,8,903.04,354.120,TEC-CO-10001191,188,5
5,IN-2013-42360,JM-15655,TEC-PH-10000030,2862.675,5,897.35,572.535,TEC-PH-10000030,2,6
6,IN-2011-81826,TS-21340,FUR-CH-10004050,1822.080,4,894.77,455.520,FUR-CH-10000660,135,7
7,IN-2012-86369,MB-18085,FUR-TA-10002958,5244.840,6,878.38,874.140,FUR-TA-10001285,136,8
8,CA-2014-135909,JW-15220,OFF-BI-10003527,5083.960,5,867.69,1016.792,OFF-BI-10003527,3,9
9,CA-2012-116638,JH-15985,FUR-TA-10000198,4297.644,13,865.74,330.588,FUR-TA-10000198,4,10

## 4    -   Tabela dim_pedidos

### Checagem pedidos duplicados

In [41]:
pedido_duplicado = pedidos['pedido_num'].value_counts()
pedido_duplicado = pedido_duplicado[pedido_duplicado > 1].index
pedidos_duplicados = pedidos[pedidos['pedido_num'].isin(pedido_duplicado)]

pedidos_duplicados.sort_values(by=['pedido_num'])

,local_pedido,ano,pedido_num,data_pedido,data_envio,modo_envio,prioridade,id_pedido
22220,TU,2014,0,2014-02-13,2014-02-19,Classe Padrao,Medio,TU-2014-0
524,AU,2011,0,2011-09-02,2011-09-02,Mesmo Dia,Critico,AU-2011-0
17475,MO,2013,0,2013-09-25,2013-09-30,Classe Padrao,Medio,MO-2013-0
1674,EN,2012,10,2012-05-28,2012-06-03,Classe Padrao,Baixo,EN-2012-10
13900,TZ,2014,10,2014-09-06,2014-09-08,Primeira Classe,Alto,TZ-2014-10
...,...,...,...,...,...,...,...,...
15899,ES,2013,1138719,2013-09-13,2013-09-18,Classe Padrao,Medio,ES-2013-1138719
13866,IT,2014,1138719,2014-04-03,2014-04-07,Classe Padrao,Alto,IT-2014-1138719
23559,ES,2011,1138719,2011-01-11,2011-01-16,Classe Padrao,Medio,ES-2011-1138719
14548,ES,2011,2911640,2011-06-28,2011-07-03,Classe Padrao,Medio,ES-2011-2911640
2576,ES,2013,2911640,2013-11-19,2013-11-21,Primeira Classe,Alto,ES-2013-2911640

### Criação da Surrogate key para tabela pedidos

In [42]:
dim_pedidos = pedidos.copy()
sk_pedido = {pedido: idx for idx, pedido in enumerate(pedidos['id_pedido'].unique(), 1)}
dim_pedidos['sk_pedido'] = pedidos['id_pedido'].map(sk_pedido)
dim_pedidos

,local_pedido,ano,pedido_num,data_pedido,data_envio,modo_envio,prioridade,id_pedido,sk_pedido
0,CA,2012,124891,2012-07-31,2012-07-31,Mesmo Dia,Critico,CA-2012-124891,1
2,IN,2013,77878,2013-02-05,2013-02-07,Segunda Classe,Critico,IN-2013-77878,2
3,IN,2013,71249,2013-10-17,2013-10-18,Primeira Classe,Medio,IN-2013-71249,3
4,ES,2013,1579342,2013-01-28,2013-01-30,Primeira Classe,Medio,ES-2013-1579342,4
5,SG,2013,4320,2013-11-05,2013-11-06,Mesmo Dia,Critico,SG-2013-4320,5
...,...,...,...,...,...,...,...,...,...
25031,ZI,2011,4350,2011-03-21,2011-03-26,Classe Padrao,Medio,ZI-2011-4350,25031
25032,MX,2014,169530,2014-06-09,2014-06-11,Primeira Classe,Alto,MX-2014-169530,25032
25033,IN,2014,72327,2014-05-30,2014-05-30,Mesmo Dia,Alto,IN-2014-72327,25033
25034,IN,2014,57662,2014-08-05,2014-08-10,Classe Padrao,Medio,IN-2014-57662,25034
25035,MX,2012,134460,2012-05-22,2012-05-26,Segunda Classe,Alto,MX-2012-134460,25035

### Merge tabela clientes x vendas_sk_clientes para inserir sk_pedido

In [43]:
vendas_sk_pedidos = vendas_sk_clientes.merge(
    dim_pedidos[['id_pedido', 'sk_pedido']],
    on='id_pedido',
    how='left'
)
vendas_sk_pedidos.head(10)

,id_pedido,id_cliente,id_produto,valor_venda,qtd_vendida,custo_envio,valor_unit,id_produto_padronizado,sk_produto,sk_cliente,sk_pedido
0,CA-2012-124891,RH-19495,TEC-AC-10003033,2309.650,7,933.57,329.950,TEC-AC-10003033,1,1,1
1,IN-2013-77878,JR-16210,FUR-CH-10003950,3709.395,9,923.63,412.155,FUR-CH-10002435,1923,2,2
2,IN-2013-71249,CR-12730,TEC-PH-10004664,5175.171,9,915.49,575.019,TEC-NOK-10000534,306,3,3
3,ES-2013-1579342,KM-16375,TEC-PH-10004583,2892.510,5,910.16,578.502,TEC-MOT-10003050,391,4,4
4,SG-2013-4320,RH-9495,TEC-SHA-10000501,2832.960,8,903.04,354.120,TEC-CO-10001191,188,5,5
5,IN-2013-42360,JM-15655,TEC-PH-10000030,2862.675,5,897.35,572.535,TEC-PH-10000030,2,6,6
6,IN-2011-81826,TS-21340,FUR-CH-10004050,1822.080,4,894.77,455.520,FUR-CH-10000660,135,7,7
7,IN-2012-86369,MB-18085,FUR-TA-10002958,5244.840,6,878.38,874.140,FUR-TA-10001285,136,8,8
8,CA-2014-135909,JW-15220,OFF-BI-10003527,5083.960,5,867.69,1016.792,OFF-BI-10003527,3,9,9
9,CA-2012-116638,JH-15985,FUR-TA-10000198,4297.644,13,865.74,330.588,FUR-TA-10000198,4,10,10

## 5    -   Tabela dim_data

Criação da Tabela

In [44]:
# Extração todas as datas únicas de ambos os campos
datas_unicas = pd.concat([
    dim_pedidos['data_pedido'], 
    dim_pedidos['data_envio']
], ignore_index=True).dropna().drop_duplicates().sort_values()

# Criação a dimensão de data
dim_data = pd.DataFrame({'data': datas_unicas})

# Gerando atributos derivados
dim_data['ano']           = dim_data['data'].dt.year
dim_data['mes']           = dim_data['data'].dt.month
dim_data['dia']           = dim_data['data'].dt.day
dim_data['dia_semana']    = dim_data['data'].dt.weekday + 1
dim_data['nome_dia_semana'] = dim_data['data'].dt.day_name()
dim_data['nome_mes']      = dim_data['data'].dt.month_name()
dim_data['ano_mes']       = dim_data['data'].dt.strftime('%Y-%m')
dim_data['trimestre']     = dim_data['data'].dt.quarter

# Gerando a surrogate key para cada data
dim_data['sk_data'] = range(1, len(dim_data)+1)

# Reordenando
colunas = ['sk_data', 'data', 'ano', 'mes', 'dia', 'dia_semana', 'nome_dia_semana', 'nome_mes', 'ano_mes', 'trimestre']
dim_data = dim_data[colunas]

dim_data

,sk_data,data,ano,mes,dia,dia_semana,nome_dia_semana,nome_mes,ano_mes,trimestre
7573,1,2011-01-01,2011,1,1,6,Saturday,January,2011-01,1
9902,2,2011-01-02,2011,1,2,7,Sunday,January,2011-01,1
2048,3,2011-01-03,2011,1,3,1,Monday,January,2011-01,1
2432,4,2011-01-04,2011,1,4,2,Tuesday,January,2011-01,1
1055,5,2011-01-05,2011,1,5,3,Wednesday,January,2011-01,1
...,...,...,...,...,...,...,...,...,...,...
25666,1464,2015-01-03,2015,1,3,6,Saturday,January,2015-01,1
30873,1465,2015-01-04,2015,1,4,7,Sunday,January,2015-01,1
30315,1466,2015-01-05,2015,1,5,1,Monday,January,2015-01,1
35563,1467,2015-01-06,2015,1,6,2,Tuesday,January,2015-01,1
37145,1468,2015-01-07,2015,1,7,3,Wednesday,January,2015-01,1

Associação a tabela dim_pedidos x sk_data_pedido

In [45]:
dim_pedidos = dim_pedidos.merge(
    dim_data[['sk_data', 'data']],
    left_on='data_pedido',
    right_on='data',
    how='left'
).rename(columns={'sk_data': 'sk_data_pedido'}).drop(columns=['data'])

dim_pedidos

,local_pedido,ano,pedido_num,data_pedido,data_envio,modo_envio,prioridade,id_pedido,sk_pedido,sk_data_pedido
0,CA,2012,124891,2012-07-31,2012-07-31,Mesmo Dia,Critico,CA-2012-124891,1,578
1,IN,2013,77878,2013-02-05,2013-02-07,Segunda Classe,Critico,IN-2013-77878,2,767
2,IN,2013,71249,2013-10-17,2013-10-18,Primeira Classe,Medio,IN-2013-71249,3,1021
3,ES,2013,1579342,2013-01-28,2013-01-30,Primeira Classe,Medio,ES-2013-1579342,4,759
4,SG,2013,4320,2013-11-05,2013-11-06,Mesmo Dia,Critico,SG-2013-4320,5,1040
...,...,...,...,...,...,...,...,...,...,...
25030,ZI,2011,4350,2011-03-21,2011-03-26,Classe Padrao,Medio,ZI-2011-4350,25031,80
25031,MX,2014,169530,2014-06-09,2014-06-11,Primeira Classe,Alto,MX-2014-169530,25032,1256
25032,IN,2014,72327,2014-05-30,2014-05-30,Mesmo Dia,Alto,IN-2014-72327,25033,1246
25033,IN,2014,57662,2014-08-05,2014-08-10,Classe Padrao,Medio,IN-2014-57662,25034,1313
25034,MX,2012,134460,2012-05-22,2012-05-26,Segunda Classe,Alto,MX-2012-134460,25035,508

Padronização de datas

In [46]:
dim_pedidos['data_pedido'] = pd.to_datetime(dim_pedidos['data_pedido']).dt.date
dim_pedidos['data_envio']  = pd.to_datetime(dim_pedidos['data_envio']).dt.date
dim_data['data'] = pd.to_datetime(dim_data['data']).dt.date

Associação a tabela dim_pedidos x sk_data_envio

In [47]:
dim_pedidos = dim_pedidos.merge(
    dim_data[['sk_data', 'data']],
    left_on='data_envio',
    right_on='data',
    how='left'
).rename(columns={'sk_data': 'sk_data_envio'}).drop(columns=['data'])
dim_pedidos

,local_pedido,ano,pedido_num,data_pedido,data_envio,modo_envio,prioridade,id_pedido,sk_pedido,sk_data_pedido,sk_data_envio
0,CA,2012,124891,2012-07-31,2012-07-31,Mesmo Dia,Critico,CA-2012-124891,1,578,578
1,IN,2013,77878,2013-02-05,2013-02-07,Segunda Classe,Critico,IN-2013-77878,2,767,769
2,IN,2013,71249,2013-10-17,2013-10-18,Primeira Classe,Medio,IN-2013-71249,3,1021,1022
3,ES,2013,1579342,2013-01-28,2013-01-30,Primeira Classe,Medio,ES-2013-1579342,4,759,761
4,SG,2013,4320,2013-11-05,2013-11-06,Mesmo Dia,Critico,SG-2013-4320,5,1040,1041
...,...,...,...,...,...,...,...,...,...,...,...
25030,ZI,2011,4350,2011-03-21,2011-03-26,Classe Padrao,Medio,ZI-2011-4350,25031,80,85
25031,MX,2014,169530,2014-06-09,2014-06-11,Primeira Classe,Alto,MX-2014-169530,25032,1256,1258
25032,IN,2014,72327,2014-05-30,2014-05-30,Mesmo Dia,Alto,IN-2014-72327,25033,1246,1246
25033,IN,2014,57662,2014-08-05,2014-08-10,Classe Padrao,Medio,IN-2014-57662,25034,1313,1318
25034,MX,2012,134460,2012-05-22,2012-05-26,Segunda Classe,Alto,MX-2012-134460,25035,508,512

##  6   -   Exclusão e Ordenação de Colunas

Exclusão de colunas dim_produtos

In [48]:
dim_produtos = dim_produtos.drop(columns=['id_produto'])

Ordernação de colunas dim_produtos

In [49]:
dim_produtos = dim_produtos.rename(columns={'id_produto_padronizado': 'id_produto'})

colunas_dim_produtos = ['sk_produto', 'id_produto', 'nome_produto'] + [
    col for col in dim_produtos.columns if col not in ['sk_produto', 'id_produto', 'nome_produto']
]
dim_produtos = dim_produtos[colunas_dim_produtos]
dim_produtos

,sk_produto,id_produto,nome_produto,categoria,subcategoria
0,1,TEC-AC-10003033,Plantronics CS510 - Over-the-Head monaural Wir...,Tecnologia,Accessories
6,2,TEC-PH-10000030,"Samsung Smart Phone, with Caller ID",Tecnologia,Phones
9,3,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,Material de Escritorio,Binders
10,4,FUR-TA-10000198,Chromcraft Bull-Nose Wood Oval Conference Tabl...,Moveis,Tables
11,5,OFF-SU-10002881,Martin Yale Chadless Opener Electric Letter Op...,Material de Escritorio,Supplies
...,...,...,...,...,...
10283,3656,OFF-SU-10001212,Kleencut Forged Office Shears by Acme United C...,Material de Escritorio,Supplies
10284,3657,OFF-AP-10004655,Holmes Visible Mist Ultrasonic Humidifier with...,Material de Escritorio,Appliances
10285,3658,OFF-ENE-10004866,"Enermax Parchment Paper, 8.5 x 11",Material de Escritorio,Paper
10291,3659,FUR-ADV-10002329,"Advantus Light Bulb, Erganomic",Moveis,Furnishings
10292,3660,OFF-AP-10002203,Eureka Disposable Bags for Sanitaire Vibra Gro...,Material de Escritorio,Appliances

Exclusão de colunas dim_pedidos

In [50]:
dim_pedidos = dim_pedidos.drop(columns=['data_pedido', 'data_envio'])

Ordenação de colunas dim_pedidos

In [51]:
colunas_dim_pedidos = ['sk_pedido', 'sk_data_pedido', 'sk_data_envio', 'id_pedido'] + [
    col for col in dim_pedidos.columns if col not in ['sk_pedido', 'sk_data_pedido', 'sk_data_envio', 'id_pedido']
]
dim_pedidos = dim_pedidos[colunas_dim_pedidos]
dim_pedidos

,sk_pedido,sk_data_pedido,sk_data_envio,id_pedido,local_pedido,ano,pedido_num,modo_envio,prioridade
0,1,578,578,CA-2012-124891,CA,2012,124891,Mesmo Dia,Critico
1,2,767,769,IN-2013-77878,IN,2013,77878,Segunda Classe,Critico
2,3,1021,1022,IN-2013-71249,IN,2013,71249,Primeira Classe,Medio
3,4,759,761,ES-2013-1579342,ES,2013,1579342,Primeira Classe,Medio
4,5,1040,1041,SG-2013-4320,SG,2013,4320,Mesmo Dia,Critico
...,...,...,...,...,...,...,...,...,...
25030,25031,80,85,ZI-2011-4350,ZI,2011,4350,Classe Padrao,Medio
25031,25032,1256,1258,MX-2014-169530,MX,2014,169530,Primeira Classe,Alto
25032,25033,1246,1246,IN-2014-72327,IN,2014,72327,Mesmo Dia,Alto
25033,25034,1313,1318,IN-2014-57662,IN,2014,57662,Classe Padrao,Medio
25034,25035,508,512,MX-2012-134460,MX,2012,134460,Segunda Classe,Alto

Ordenação de colunas dim_clientes

In [52]:
coluna_dim_clientes = ['sk_cliente'] + [
    col for col in dim_clientes.columns if col not in ['sk_cliente']
]
dim_clientes = dim_clientes[coluna_dim_clientes]
dim_clientes

,sk_cliente,id_cliente,nome_cliente,segmento,cidade,estado,pais,mercado,regiao
0,1,RH-19495,Rick Hansen,Consumidor,New York City,New York,United States,US,East
1,2,JR-16210,Justin Ritter,Corporativo,Wollongong,New South Wales,Australia,APAC,Oceania
2,3,CR-12730,Craig Reiter,Consumidor,Brisbane,Queensland,Australia,APAC,Oceania
3,4,KM-16375,Katherine Murray,Outros,Berlin,Berlin,Germany,EU,Central
4,5,RH-9495,Rick Hansen,Consumidor,Dakar,Dakar,Senegal,Africa,Africa
...,...,...,...,...,...,...,...,...,...
1585,1586,SC-10800,Stuart Calhoun,Consumidor,Benin City,Edo,Nigeria,Africa,Africa
1586,1587,BD-1500,Bradley Drucker,Consumidor,Lagos,Lagos,Nigeria,Africa,Africa
1587,1588,RC-9825,Roy Collins,Consumidor,Budapest,Budapest,Hungary,EMEA,EMEA
1588,1589,MG-7890,Michael Granlund,Outros,Istanbul,Istanbul,Turkey,EMEA,EMEA
1589,1590,ZC-11910,Zuschuss Carroll,Consumidor,Maiduguri,Borno,Nigeria,Africa,Africa

Exclusão de colunas fato_vendas

In [53]:
fato_vendas = vendas_sk_pedidos.drop(columns=['id_pedido', 'id_cliente', 'id_produto', 'id_produto_padronizado'])
fato_vendas

,valor_venda,qtd_vendida,custo_envio,valor_unit,sk_produto,sk_cliente,sk_pedido
0,2309.650,7,933.57,329.950,1,1,1
1,3709.395,9,923.63,412.155,1923,2,2
2,5175.171,9,915.49,575.019,306,3,3
3,2892.510,5,910.16,578.502,391,4,4
4,2832.960,8,903.04,354.120,188,5,5
...,...,...,...,...,...,...,...
51285,65.100,5,0.01,13.020,2588,666,1465
51286,0.444,1,0.01,0.444,3631,45,13946
51287,22.920,3,0.01,7.640,3112,24,4607
51288,13.440,2,0.00,6.720,2916,256,2748
51289,61.380,3,0.00,20.460,1984,658,25035

In [54]:
contagem = fato_vendas['sk_pedido'].value_counts().reset_index()
contagem.columns = ['sk_pedido', 'Quantidade']
num_fato_vendas_repetidos = contagem[contagem['Quantidade'] > 1]
num_fato_vendas_repetidos

       sk_pedido  Quantidade
0           1206          14
1           7884          13
2          13042          13
3           2848          13
4           8511          13
...          ...         ...
12773      24993           2
12774         15           2
12775         14           2
12776          7           2
12777       6569           2

[12778 rows x 2 columns]

In [55]:
dim_pedidos[dim_pedidos['sk_pedido'] == 1206]

,sk_pedido,sk_data_pedido,sk_data_envio,id_pedido,local_pedido,ano,pedido_num,modo_envio,prioridade
1205,1206,1360,1366,CA-2014-100111,CA,2014,100111,Classe Padrao,Medio

Ordenação de colunas fato_vendas

In [56]:
coluna_fato_vendas = ['sk_pedido', 'sk_cliente', 'sk_produto'] + [
    col for col in fato_vendas.columns if col not in ['sk_pedido', 'sk_cliente', 'sk_produto']
]
fato_vendas = fato_vendas[coluna_fato_vendas]
fato_vendas.describe()

,sk_pedido,sk_cliente,sk_produto,valor_venda,qtd_vendida,custo_envio,valor_unit
count,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,10541.223962,582.158120,1786.192630,246.490581,3.476545,26.375915,71.657487
std,6939.914535,390.131567,999.477495,487.565361,2.278766,57.296804,113.581515
min,1.000000,1.000000,1.000000,0.444000,1.000000,0.000000,0.336000
25%,4508.000000,256.000000,943.000000,30.758625,2.000000,2.610000,11.799900
50%,9757.000000,537.000000,1806.000000,85.053000,3.000000,7.790000,29.400000
75%,16035.000000,849.000000,2632.000000,251.053200,5.000000,24.450000,82.160000
max,25035.000000,1590.000000,3660.000000,22638.480000,14.000000,933.570000,3773.080000

## 7 - Outliers

IQR

In [57]:
for coluna in ['valor_venda', 'custo_envio', 'valor_unit']:
    Q1 = fato_vendas[coluna].quantile(0.25)
    Q3 = fato_vendas[coluna].quantile(0.75)
    IQR = Q3 - Q1
    lim_inf = Q1 - 1.5 * IQR
    lim_sup = Q3 + 1.5 * IQR
    outliers = fato_vendas[(fato_vendas[coluna] < lim_inf) | (fato_vendas[coluna] > lim_sup)]
    print(f"\n--- Outliers em {coluna} ---")
    print(outliers[[coluna, 'sk_pedido', 'sk_produto']])
    print(f"Qtd de outliers em {coluna}: {outliers.shape[0]}")

--- Outliers em valor_venda ---
       valor_venda  sk_pedido  sk_produto
0         2309.650          1           1
1         3709.395          2        1923
2         5175.171          3         306
3         2892.510          4         391
4         2832.960          5         188
...            ...        ...         ...
44220     1585.710       7740        1009
45234      618.084       2529         775
45351      936.270      23441        1216
47131      607.360      17173         135
50402      772.470      20816          64

[5655 rows x 3 columns]
Qtd de outliers em valor_venda: 5655

--- Outliers em custo_envio ---
      custo_envio  sk_pedido  sk_produto
0          933.57          1           1
1          923.63          2        1923
2          915.49          3         306
3          910.16          4         391
4          903.04          5         188
...           ...        ...         ...
5904        57.26       5082         613
5905        57.25        718         776
5906        57.23       5083         164
5907        57.21       5084        1137
5908        57.21       5085         104

[5909 rows x 3 columns]
Qtd de outliers em custo_envio: 5909

--- Outliers em valor_unit ---
       valor_unit  sk_pedido  sk_produto
0         329.950          1           1
1         412.155          2        1923
2         575.019          3         306
3         578.502          4         391
4         354.120          5         188
...           ...        ...         ...
45351     312.090      23441        1216
46629     198.090       6618         348
46885     278.460       1701         296
47131     303.680      17173         135
50402     257.490      20816          64

[5022 rows x 3 columns]
Qtd de outliers em valor_unit: 5022

Z-Score

In [58]:
for coluna in ['valor_venda', 'custo_envio', 'valor_unit']:
    media = fato_vendas[coluna].mean()
    std = fato_vendas[coluna].std()
    threshold = 3  # padrão: considera outlier acima de 3 desvios
    outliers = fato_vendas[np.abs(fato_vendas[coluna] - media) > threshold * std]
    print(f"\n--- Outliers em {coluna} pelo Z-score ---")
    print(outliers[[coluna, 'sk_pedido', 'sk_produto']])
    print(f"Qtd de outliers em {coluna}: {outliers.shape[0]}")

--- Outliers em valor_venda pelo Z-score ---
       valor_venda  sk_pedido  sk_produto
0         2309.650          1           1
1         3709.395          2        1923
2         5175.171          3         306
3         2892.510          4         391
4         2832.960          5         188
...            ...        ...         ...
22238     4799.984      11176          66
30439     2039.796       8132          62
37133     1840.680      10749         503
39410     1809.780       8480        1001
39564     5724.540      21691          88

[1020 rows x 3 columns]
Qtd de outliers em valor_venda: 1020

--- Outliers em custo_envio pelo Z-score ---
      custo_envio  sk_pedido  sk_produto
0          933.57          1           1
1          923.63          2        1923
2          915.49          3         306
3          910.16          4         391
4          903.04          5         188
...           ...        ...         ...
1036       199.04        989         190
1037       198.47        695         824
1038       198.39        990         534
1039       198.28        991        1990
1040       198.27        992         376

[1041 rows x 3 columns]
Qtd de outliers em custo_envio: 1041

--- Outliers em valor_unit pelo Z-score ---
       valor_unit  sk_pedido  sk_produto
2         575.019          3         306
3         578.502          4         391
5         572.535          6           2
6         455.520          7         135
7         874.140          8         136
...           ...        ...         ...
37242     436.160      12316           6
39564     636.060      21691          88
41211     546.363      11582         391
41227     550.980      10289           4
42191     542.340      22507         225

[1171 rows x 3 columns]
Qtd de outliers em valor_unit: 1171

# Carga

In [59]:
dim_produtos.to_csv('dados/dim_produtos.csv', index=False, encoding='utf-8')
dim_clientes.to_csv('dados/dim_clientes.csv', index=False, encoding='utf-8')
dim_pedidos.to_csv('dados/dim_pedidos.csv', index=False, encoding='utf-8')
dim_data.to_csv('dados/dim_data.csv', index=False, encoding='utf-8')
fato_vendas.to_csv('dados/fato_vendas.csv', index=False, encoding='utf-8')